var hierarchy =
[
    [ "tess::ActiveMask", "structtess_1_1ActiveMask.html", null ],
    [ "tess::AdjacentTransitions", "structtess_1_1AdjacentTransitions.html", null ],
    [ "tess::AgentId", "structtess_1_1AgentId.html", null ],
    [ "tess::diagnostics::AllocationCounters", "structtess_1_1diagnostics_1_1AllocationCounters.html", null ],
    [ "tess::movement::AllOf&lt; Terms &gt;", "structtess_1_1movement_1_1AllOf.html", null ],
    [ "tess::AlwaysResident", "structtess_1_1AlwaysResident.html", null ],
    [ "tess::movement::AnyOf&lt; Terms &gt;", "structtess_1_1movement_1_1AnyOf.html", null ],
    [ "tess::AreaBuildResult", "structtess_1_1AreaBuildResult.html", null ],
    [ "tess::AreaConnection", "structtess_1_1AreaConnection.html", null ],
    [ "tess::AreaId", "structtess_1_1AreaId.html", null ],
    [ "tess::AreaIndex", "classtess_1_1AreaIndex.html", null ],
    [ "tess::AreaIndexScratch", "classtess_1_1AreaIndexScratch.html", null ],
    [ "tess::AreaSummary", "structtess_1_1AreaSummary.html", null ],
    [ "tess::AsyncAdvanceStats", "structtess_1_1AsyncAdvanceStats.html", null ],
    [ "tess::AsyncTicket", "structtess_1_1AsyncTicket.html", null ],
    [ "tess::AsyncVersion", "structtess_1_1AsyncVersion.html", null ],
    [ "tess::AsyncWorkBudget", "structtess_1_1AsyncWorkBudget.html", null ],
    [ "tess::AsyncWorkStep", "structtess_1_1AsyncWorkStep.html", null ],
    [ "tess::AutoExecRunStats", "structtess_1_1AutoExecRunStats.html", null ],
    [ "tess::AutoExecTask&lt; World, Policy, Ack, ChunkFn &gt;", "classtess_1_1AutoExecTask.html", null ],
    [ "tess::BackgroundBudget", "structtess_1_1BackgroundBudget.html", null ],
    [ "tess::BlockCtx&lt; World, Policy &gt;", "classtess_1_1BlockCtx.html", null ],
    [ "tess::BlockDiagnostics", "classtess_1_1BlockDiagnostics.html", null ],
    [ "tess::BlockedAgentRecoveryOptions", "structtess_1_1BlockedAgentRecoveryOptions.html", null ],
    [ "tess::BlockedAgentRecoverySchedule", "classtess_1_1BlockedAgentRecoverySchedule.html", null ],
    [ "tess::BlockedAgentRecoveryStats", "structtess_1_1BlockedAgentRecoveryStats.html", null ],
    [ "tess::BlockScratch", "classtess_1_1BlockScratch.html", null ],
    [ "tess::BlockTile&lt; ChunkView &gt;", "structtess_1_1BlockTile.html", null ],
    [ "tess::debug::imgui::BoolFieldEditIntent", "structtess_1_1debug_1_1imgui_1_1BoolFieldEditIntent.html", null ],
    [ "tess::debug::imgui::BoolFieldEditResult", "structtess_1_1debug_1_1imgui_1_1BoolFieldEditResult.html", null ],
    [ "tess::Box3", "structtess_1_1Box3.html", null ],
    [ "tess::diagnostics::BufferedWarningSink&lt; Capacity &gt;", "classtess_1_1diagnostics_1_1BufferedWarningSink.html", null ],
    [ "tess::Cadence", "structtess_1_1Cadence.html", null ],
    [ "tess::ChunkCoord3", "structtess_1_1ChunkCoord3.html", null ],
    [ "tess::ChunkDomain", "classtess_1_1ChunkDomain.html", null ],
    [ "tess::ChunkKey", "structtess_1_1ChunkKey.html", null ],
    [ "tess::experimental::maintenance::ChunkMaintenanceAdapter&lt; World, Product, Rebuild, Backend &gt;", "classtess_1_1experimental_1_1maintenance_1_1ChunkMaintenanceAdapter.html", null ],
    [ "tess::ChunkMeta", "structtess_1_1ChunkMeta.html", null ],
    [ "tess::ChunkPage&lt; Shape, Schema &gt;", "classtess_1_1ChunkPage.html", null ],
    [ "tess::ChunkPage&lt; Shape, FieldSchema&lt; Fields... &gt; &gt;", "classtess_1_1ChunkPage_3_01Shape_00_01FieldSchema_3_01Fields_8_8_8_01_4_01_4.html", null ],
    [ "tess::experimental::maintenance::ChunkProductToken", "structtess_1_1experimental_1_1maintenance_1_1ChunkProductToken.html", null ],
    [ "tess::experimental::maintenance::ChunkProductView&lt; Product &gt;", "structtess_1_1experimental_1_1maintenance_1_1ChunkProductView.html", null ],
    [ "tess::experimental::maintenance::ChunkResidencyResult", "structtess_1_1experimental_1_1maintenance_1_1ChunkResidencyResult.html", null ],
    [ "tess::ChunkView&lt; World &gt;", "classtess_1_1ChunkView.html", null ],
    [ "tess::WeightedPortalSegmentCache::ClassView&lt; Class &gt;", "classtess_1_1WeightedPortalSegmentCache_1_1ClassView.html", null ],
    [ "tess::CoarsePathResult", "structtess_1_1CoarsePathResult.html", null ],
    [ "tess::movement::ConstantCost&lt; N &gt;", "structtess_1_1movement_1_1ConstantCost.html", null ],
    [ "tess::ContentVersion", "structtess_1_1ContentVersion.html", null ],
    [ "tess::ContentVersionDependencies", "classtess_1_1ContentVersionDependencies.html", null ],
    [ "tess::ContentVersionDependencies::ContentVersionDependency", "structtess_1_1ContentVersionDependencies_1_1ContentVersionDependency.html", null ],
    [ "tess::Coord2", "structtess_1_1Coord2.html", null ],
    [ "tess::Coord3", "structtess_1_1Coord3.html", null ],
    [ "tess::movement::DefaultSteps", "structtess_1_1movement_1_1DefaultSteps.html", null ],
    [ "tess::DeltaCollector", "classtess_1_1DeltaCollector.html", null ],
    [ "tess::DeltaCollectorOptions", "structtess_1_1DeltaCollectorOptions.html", null ],
    [ "tess::DeltaCollectorStats", "structtess_1_1DeltaCollectorStats.html", null ],
    [ "tess::DeltaFrame", "classtess_1_1DeltaFrame.html", null ],
    [ "tess::DeltaFrameHeader", "structtess_1_1DeltaFrameHeader.html", null ],
    [ "tess::diagnostics::DiagnosticsSnapshot", "structtess_1_1diagnostics_1_1DiagnosticsSnapshot.html", null ],
    [ "tess::movement::DiagonalSteps&lt; Rule &gt;", "structtess_1_1movement_1_1DiagonalSteps.html", null ],
    [ "tess::DirtyMask", "structtess_1_1DirtyMask.html", null ],
    [ "tess::DirtyObservation", "structtess_1_1DirtyObservation.html", null ],
    [ "tess::gpu::DispatchDesc", "structtess_1_1gpu_1_1DispatchDesc.html", null ],
    [ "tess::DistanceFieldProduct", "classtess_1_1DistanceFieldProduct.html", null ],
    [ "tess::DistanceFieldResult", "structtess_1_1DistanceFieldResult.html", null ],
    [ "tess::DistanceFieldScratch", "classtess_1_1DistanceFieldScratch.html", null ],
    [ "tess::DomainDesc", "classtess_1_1DomainDesc.html", null ],
    [ "tess::EntityDelta", "structtess_1_1EntityDelta.html", null ],
    [ "tess::EntityHandle", "structtess_1_1EntityHandle.html", null ],
    [ "tess::EnttAgentEntry", "structtess_1_1EnttAgentEntry.html", null ],
    [ "tess::EnttHandleAdapter", "structtess_1_1EnttHandleAdapter.html", null ],
    [ "tess::EnttPathAgentContext", "structtess_1_1EnttPathAgentContext.html", null ],
    [ "tess::EnttPathAgentSink&lt; Position &gt;", "classtess_1_1EnttPathAgentSink.html", null ],
    [ "tess::EnttPathAgentSource", "classtess_1_1EnttPathAgentSource.html", null ],
    [ "tess::EnttTilePositionAdapter", "classtess_1_1EnttTilePositionAdapter.html", null ],
    [ "tess::EventStream&lt; T &gt;", "classtess_1_1EventStream.html", null ],
    [ "tess::ExecutionPhase", "classtess_1_1ExecutionPhase.html", null ],
    [ "tess::ExecutionPhasePlan", "classtess_1_1ExecutionPhasePlan.html", null ],
    [ "tess::ExecutionPlan", "classtess_1_1ExecutionPlan.html", null ],
    [ "tess::ExecutionReport", "classtess_1_1ExecutionReport.html", null ],
    [ "tess::ExecutorPhaseRange", "structtess_1_1ExecutorPhaseRange.html", null ],
    [ "tess::Extent3", "structtess_1_1Extent3.html", null ],
    [ "tess::Field&lt; Tag, Value &gt;", "structtess_1_1Field.html", null ],
    [ "tess::movement::Field&lt; Tag &gt;", "structtess_1_1movement_1_1Field.html", null ],
    [ "tess::FieldAccessDesc", "structtess_1_1FieldAccessDesc.html", null ],
    [ "tess::movement::FieldCost&lt; CostTag &gt;", "structtess_1_1movement_1_1FieldCost.html", null ],
    [ "tess::gpu::FieldMirrorDesc", "structtess_1_1gpu_1_1FieldMirrorDesc.html", null ],
    [ "tess::FieldProductCache", "classtess_1_1FieldProductCache.html", null ],
    [ "tess::FieldProductCacheStats", "structtess_1_1FieldProductCacheStats.html", null ],
    [ "tess::FieldProductDesc", "structtess_1_1FieldProductDesc.html", null ],
    [ "tess::FieldSchema&lt; Fields &gt;", "structtess_1_1FieldSchema.html", null ],
    [ "tess::FixedStepAccumulator", "classtess_1_1FixedStepAccumulator.html", null ],
    [ "tess::FixedStepFrame", "structtess_1_1FixedStepFrame.html", null ],
    [ "tess::FlecsAgentEntry", "structtess_1_1FlecsAgentEntry.html", null ],
    [ "tess::FlecsHandleAdapter", "structtess_1_1FlecsHandleAdapter.html", null ],
    [ "tess::FlecsPathAgentContext", "structtess_1_1FlecsPathAgentContext.html", null ],
    [ "tess::FlecsPathAgentSink&lt; Position &gt;", "classtess_1_1FlecsPathAgentSink.html", null ],
    [ "tess::FlecsPathAgentSource", "classtess_1_1FlecsPathAgentSource.html", null ],
    [ "tess::FlecsTilePositionAdapter", "classtess_1_1FlecsTilePositionAdapter.html", null ],
    [ "tess::diagnostics::FlowAccounting", "structtess_1_1diagnostics_1_1FlowAccounting.html", null ],
    [ "tess::diagnostics::FlowCounters", "structtess_1_1diagnostics_1_1FlowCounters.html", null ],
    [ "tess::diagnostics::FlowHealthSnapshot", "structtess_1_1diagnostics_1_1FlowHealthSnapshot.html", null ],
    [ "tess::GoalSet", "classtess_1_1GoalSet.html", null ],
    [ "tess::gpu::GpuCapabilities", "structtess_1_1gpu_1_1GpuCapabilities.html", null ],
    [ "tess::gpu::GpuProductHandle", "structtess_1_1gpu_1_1GpuProductHandle.html", null ],
    [ "tess::lattice::HexAxial", "structtess_1_1lattice_1_1HexAxial.html", null ],
    [ "tess::HexCoord", "structtess_1_1HexCoord.html", null ],
    [ "tess::IntentInvalidations", "structtess_1_1IntentInvalidations.html", null ],
    [ "tess::IntentMetadata", "structtess_1_1IntentMetadata.html", null ],
    [ "tess::IntentPayloadView", "structtess_1_1IntentPayloadView.html", null ],
    [ "tess::IntentVersions", "structtess_1_1IntentVersions.html", null ],
    [ "tess::JointMoveOptions", "structtess_1_1JointMoveOptions.html", null ],
    [ "tess::JointMoveScratch", "structtess_1_1JointMoveScratch.html", null ],
    [ "tess::JointMoveStats", "structtess_1_1JointMoveStats.html", null ],
    [ "tess::LocalBoundaryExit", "structtess_1_1LocalBoundaryExit.html", null ],
    [ "tess::LocalChunkTopology", "classtess_1_1LocalChunkTopology.html", null ],
    [ "tess::LocalCongestion", "structtess_1_1LocalCongestion.html", null ],
    [ "tess::LocalCoord3", "structtess_1_1LocalCoord3.html", null ],
    [ "tess::LocalCoordinationResult", "structtess_1_1LocalCoordinationResult.html", null ],
    [ "tess::LocalCoordinationScratch", "classtess_1_1LocalCoordinationScratch.html", null ],
    [ "tess::LocalMoveDecision", "structtess_1_1LocalMoveDecision.html", null ],
    [ "tess::LocalMoveOption", "structtess_1_1LocalMoveOption.html", null ],
    [ "tess::LocalMoveRequest", "structtess_1_1LocalMoveRequest.html", null ],
    [ "tess::LocalRegion", "structtess_1_1LocalRegion.html", null ],
    [ "tess::LocalRegionId", "structtess_1_1LocalRegionId.html", null ],
    [ "tess::LocalTileId", "structtess_1_1LocalTileId.html", null ],
    [ "tess::LocalTopologyScratch", "classtess_1_1LocalTopologyScratch.html", null ],
    [ "tess::experimental::maintenance::MaintenanceBudget", "classtess_1_1experimental_1_1maintenance_1_1MaintenanceBudget.html", null ],
    [ "tess::experimental::maintenance::MaintenanceHandle", "classtess_1_1experimental_1_1maintenance_1_1MaintenanceHandle.html", null ],
    [ "tess::experimental::maintenance::MaintenanceMetrics", "structtess_1_1experimental_1_1maintenance_1_1MaintenanceMetrics.html", null ],
    [ "tess::experimental::maintenance::MaintenanceScheduler", "classtess_1_1experimental_1_1maintenance_1_1MaintenanceScheduler.html", [
      [ "tess::experimental::maintenance::DirtyBitScheduler", "classtess_1_1experimental_1_1maintenance_1_1DirtyBitScheduler.html", null ],
      [ "tess::experimental::maintenance::ImmediateScheduler", "classtess_1_1experimental_1_1maintenance_1_1ImmediateScheduler.html", null ]
    ] ],
    [ "tess::experimental::maintenance::MaintenanceTask", "classtess_1_1experimental_1_1maintenance_1_1MaintenanceTask.html", null ],
    [ "tess::MarkDirtyDesc", "structtess_1_1MarkDirtyDesc.html", null ],
    [ "tess::MoveBatchDesc", "structtess_1_1MoveBatchDesc.html", null ],
    [ "tess::movement::movement_class_tag", "structtess_1_1movement_1_1movement__class__tag.html", [
      [ "tess::movement::MovementClass< AllOf< Field< PassableTag >, NotZero< CostTag > >, FieldCost< CostTag > >", "structtess_1_1movement_1_1MovementClass.html", [
        [ "tess::movement::PositiveCostFieldMovement< PassableTag, CostTag >", "structtess_1_1movement_1_1PositiveCostFieldMovement.html", null ]
      ] ],
      [ "tess::movement::MovementClass< Field< PassableTag >, UnitCost >", "structtess_1_1movement_1_1MovementClass.html", [
        [ "tess::movement::UnitCostFieldMovement< PassableTag >", "structtess_1_1movement_1_1UnitCostFieldMovement.html", null ]
      ] ],
      [ "tess::movement::MovementClass< PassExpr, CostExpr, StepPolicyT >", "structtess_1_1movement_1_1MovementClass.html", null ]
    ] ],
    [ "tess::MovementFailureCounts", "structtess_1_1MovementFailureCounts.html", null ],
    [ "tess::MovementIntent", "structtess_1_1MovementIntent.html", null ],
    [ "tess::MovementResult", "structtess_1_1MovementResult.html", null ],
    [ "tess::MovementVersionCheck", "structtess_1_1MovementVersionCheck.html", null ],
    [ "tess::NearestBatchDesc", "structtess_1_1NearestBatchDesc.html", null ],
    [ "tess::NearestBatchHandle", "structtess_1_1NearestBatchHandle.html", null ],
    [ "tess::NearestTargetResult", "structtess_1_1NearestTargetResult.html", null ],
    [ "tess::gpu::NoGpuBackend", "structtess_1_1gpu_1_1NoGpuBackend.html", null ],
    [ "tess::movement::Not&lt; Term &gt;", "structtess_1_1movement_1_1Not.html", null ],
    [ "tess::movement::NotZero&lt; Tag &gt;", "structtess_1_1movement_1_1NotZero.html", null ],
    [ "tess::diagnostics::NullWarningSink", "structtess_1_1diagnostics_1_1NullWarningSink.html", null ],
    [ "tess::OffBoard", "structtess_1_1OffBoard.html", null ],
    [ "tess::OpCompletion", "structtess_1_1OpCompletion.html", null ],
    [ "tess::PathScratch::OpenNode", "structtess_1_1PathScratch_1_1OpenNode.html", null ],
    [ "tess::OperationAccess", "structtess_1_1OperationAccess.html", null ],
    [ "tess::OperationBatch", "classtess_1_1OperationBatch.html", null ],
    [ "tess::OperationReport", "structtess_1_1OperationReport.html", null ],
    [ "tess::OpHandle", "structtess_1_1OpHandle.html", null ],
    [ "tess::OpId", "structtess_1_1OpId.html", null ],
    [ "tess::lattice::Orthogonal", "structtess_1_1lattice_1_1Orthogonal.html", null ],
    [ "tess::OwnedChunkDomain", "classtess_1_1OwnedChunkDomain.html", null ],
    [ "tess::PathAgentAdvanceOptions", "structtess_1_1PathAgentAdvanceOptions.html", null ],
    [ "tess::PathAgentBatch", "classtess_1_1PathAgentBatch.html", null ],
    [ "tess::PathAgentCollectInfo", "structtess_1_1PathAgentCollectInfo.html", null ],
    [ "tess::PathAgentFrameStats", "structtess_1_1PathAgentFrameStats.html", null ],
    [ "tess::PathAgentReplanOptions", "structtess_1_1PathAgentReplanOptions.html", null ],
    [ "tess::PathAgentReplanQueue", "classtess_1_1PathAgentReplanQueue.html", null ],
    [ "tess::PathAgentRoutes", "structtess_1_1PathAgentRoutes.html", null ],
    [ "tess::PathAgentState", "structtess_1_1PathAgentState.html", null ],
    [ "tess::PathAgentTickOptions", "structtess_1_1PathAgentTickOptions.html", null ],
    [ "tess::PathAgentTickState", "structtess_1_1PathAgentTickState.html", null ],
    [ "tess::PathAgentTickStats", "structtess_1_1PathAgentTickStats.html", null ],
    [ "tess::PathBatchDesc", "structtess_1_1PathBatchDesc.html", null ],
    [ "tess::PathBatchHandle", "structtess_1_1PathBatchHandle.html", null ],
    [ "tess::diagnostics::PathCounters", "structtess_1_1diagnostics_1_1PathCounters.html", null ],
    [ "tess::PathGoal", "structtess_1_1PathGoal.html", null ],
    [ "tess::PathOverlayDelta", "structtess_1_1PathOverlayDelta.html", null ],
    [ "tess::PathRequest", "structtess_1_1PathRequest.html", null ],
    [ "tess::PathRequestRuntime", "classtess_1_1PathRequestRuntime.html", null ],
    [ "tess::PathResult", "structtess_1_1PathResult.html", null ],
    [ "tess::PathRuntimeCachePolicy", "structtess_1_1PathRuntimeCachePolicy.html", null ],
    [ "tess::PathRuntimeStats", "structtess_1_1PathRuntimeStats.html", null ],
    [ "tess::PathScratch", "classtess_1_1PathScratch.html", null ],
    [ "tess::PathState", "structtess_1_1PathState.html", null ],
    [ "tess::PathTicket", "structtess_1_1PathTicket.html", null ],
    [ "tess::PathTieBreak", "structtess_1_1PathTieBreak.html", null ],
    [ "tess::PathView", "classtess_1_1PathView.html", null ],
    [ "tess::PersistedField&lt; Tag, Id, Version &gt;", "structtess_1_1PersistedField.html", null ],
    [ "tess::PersistenceSchema&lt; Id, Version, Fields &gt;", "structtess_1_1PersistenceSchema.html", null ],
    [ "tess::PhaseDirtyPartition", "classtess_1_1PhaseDirtyPartition.html", null ],
    [ "tess::PibtPriorities", "structtess_1_1PibtPriorities.html", null ],
    [ "tess::Pipeline&lt; Source &gt;", "classtess_1_1Pipeline.html", null ],
    [ "tess::PipelineCollectResult", "structtess_1_1PipelineCollectResult.html", null ],
    [ "tess::PipelineDiagnostics", "classtess_1_1PipelineDiagnostics.html", null ],
    [ "tess::PlannedDirtyAccumulator", "classtess_1_1PlannedDirtyAccumulator.html", null ],
    [ "tess::PlannedDirtyCollectResult", "structtess_1_1PlannedDirtyCollectResult.html", null ],
    [ "tess::PlannedDirtyMergeResult", "structtess_1_1PlannedDirtyMergeResult.html", null ],
    [ "tess::PlannedDirtyPartitions", "classtess_1_1PlannedDirtyPartitions.html", null ],
    [ "tess::PlannedDirtyRecord", "structtess_1_1PlannedDirtyRecord.html", null ],
    [ "tess::PlannedExecutionResult", "structtess_1_1PlannedExecutionResult.html", null ],
    [ "tess::PlannedOperation", "classtess_1_1PlannedOperation.html", null ],
    [ "tess::PlannedOperationCreateResult", "structtess_1_1PlannedOperationCreateResult.html", null ],
    [ "tess::PlannedPhaseExecutionScratch", "classtess_1_1PlannedPhaseExecutionScratch.html", null ],
    [ "tess::PortalSegmentCacheStats", "structtess_1_1PortalSegmentCacheStats.html", null ],
    [ "tess::QueuedOperation", "structtess_1_1QueuedOperation.html", null ],
    [ "tess::diagnostics::QueuedPhaseCounters", "structtess_1_1diagnostics_1_1QueuedPhaseCounters.html", null ],
    [ "tess::ReachabilityResult", "structtess_1_1ReachabilityResult.html", null ],
    [ "tess::gpu::ReadbackDesc", "structtess_1_1gpu_1_1ReadbackDesc.html", null ],
    [ "tess::RegionGraphBuildResult", "structtess_1_1RegionGraphBuildResult.html", null ],
    [ "tess::RegionGraphScratch", "classtess_1_1RegionGraphScratch.html", null ],
    [ "tess::RegionGraphT&lt; Residency &gt;", "classtess_1_1RegionGraphT.html", null ],
    [ "tess::RegionPortal", "structtess_1_1RegionPortal.html", null ],
    [ "tess::RegionRef", "structtess_1_1RegionRef.html", null ],
    [ "tess::experimental::maintenance::RegisteredScheduler&lt; Backend &gt;", "classtess_1_1experimental_1_1maintenance_1_1RegisteredScheduler.html", null ],
    [ "tess::RenderDeltaDesc", "structtess_1_1RenderDeltaDesc.html", null ],
    [ "tess::RenderTileDelta", "structtess_1_1RenderTileDelta.html", null ],
    [ "tess::RenderVersion", "structtess_1_1RenderVersion.html", null ],
    [ "tess::ResidencyConfig", "structtess_1_1ResidencyConfig.html", null ],
    [ "tess::ResidencyDesc", "structtess_1_1ResidencyDesc.html", null ],
    [ "tess::ResidencyGeneration", "structtess_1_1ResidencyGeneration.html", null ],
    [ "tess::ResidencyHandle", "structtess_1_1ResidencyHandle.html", null ],
    [ "tess::World&lt; Shape, Schema, SparseResident &gt;::ResidentChunkRef", "structtess_1_1World_3_01Shape_00_01Schema_00_01SparseResident_01_4_1_1ResidentChunkRef.html", null ],
    [ "tess::ResolvedTile&lt; Shape &gt;", "structtess_1_1ResolvedTile.html", null ],
    [ "tess::ResolvedTransitionModel&lt; World, ClassOrTag, Provider &gt;", "classtess_1_1ResolvedTransitionModel.html", null ],
    [ "tess::ResultChannel&lt; T &gt;", "classtess_1_1ResultChannel.html", null ],
    [ "tess::ResumableWorkQueue&lt; T &gt;", "classtess_1_1ResumableWorkQueue.html", null ],
    [ "tess::ResumableWorkTask&lt; T &gt;", "classtess_1_1ResumableWorkTask.html", null ],
    [ "tess::RouteAttachmentRanking", "structtess_1_1RouteAttachmentRanking.html", null ],
    [ "tess::Schedule", "classtess_1_1Schedule.html", null ],
    [ "tess::ScheduleFrameSummary", "structtess_1_1ScheduleFrameSummary.html", null ],
    [ "tess::ScheduleTaskContext", "structtess_1_1ScheduleTaskContext.html", null ],
    [ "tess::ScheduleTaskDesc", "structtess_1_1ScheduleTaskDesc.html", null ],
    [ "tess::ScheduleTaskResult", "structtess_1_1ScheduleTaskResult.html", null ],
    [ "tess::ScheduleTaskStats", "structtess_1_1ScheduleTaskStats.html", null ],
    [ "tess::ScheduleTickStats", "structtess_1_1ScheduleTickStats.html", null ],
    [ "tess::diagnostics::ScopedAllocationCounters", "classtess_1_1diagnostics_1_1ScopedAllocationCounters.html", null ],
    [ "tess::diagnostics::ScopedPathCounters", "classtess_1_1diagnostics_1_1ScopedPathCounters.html", null ],
    [ "tess::diagnostics::ScopedQueuedPhaseCounters", "classtess_1_1diagnostics_1_1ScopedQueuedPhaseCounters.html", null ],
    [ "tess::ScopedThreadPhaseExecutorImpl&lt; CaptureExceptions &gt;", "classtess_1_1ScopedThreadPhaseExecutorImpl.html", null ],
    [ "tess::diagnostics::ScopedTimer", "classtess_1_1diagnostics_1_1ScopedTimer.html", null ],
    [ "tess::diagnostics::ScopedTrace", "classtess_1_1diagnostics_1_1ScopedTrace.html", null ],
    [ "tess::SegmentHit", "structtess_1_1SegmentHit.html", null ],
    [ "tess::movement::SelectCost&lt; SelTag, WhenSet, WhenClear &gt;", "structtess_1_1movement_1_1SelectCost.html", null ],
    [ "tess::SerialPhaseExecutor", "structtess_1_1SerialPhaseExecutor.html", null ],
    [ "tess::Shape&lt; Size, Chunk, Lattice &gt;", "structtess_1_1Shape.html", null ],
    [ "tess::ShapeTraits&lt; Shape &gt;", "structtess_1_1ShapeTraits.html", null ],
    [ "tess::SimClock", "structtess_1_1SimClock.html", null ],
    [ "tess::SimSchedulerOptions", "structtess_1_1SimSchedulerOptions.html", null ],
    [ "tess::SimSchedulerState", "structtess_1_1SimSchedulerState.html", null ],
    [ "tess::SimSchedulerStats", "structtess_1_1SimSchedulerStats.html", null ],
    [ "tess::SimTimeControl", "structtess_1_1SimTimeControl.html", null ],
    [ "tess::SpanQueryStats", "structtess_1_1SpanQueryStats.html", null ],
    [ "tess::SparseResident", "structtess_1_1SparseResident.html", null ],
    [ "tess::SpecialTransitionCandidate", "structtess_1_1SpecialTransitionCandidate.html", null ],
    [ "tess::StairTransitions&lt; StairTag &gt;", "structtess_1_1StairTransitions.html", null ],
    [ "tess::TacticalAssignment", "structtess_1_1TacticalAssignment.html", null ],
    [ "tess::TacticalAssignmentResult", "structtess_1_1TacticalAssignmentResult.html", null ],
    [ "tess::TacticalAssignmentScratch", "classtess_1_1TacticalAssignmentScratch.html", null ],
    [ "tess::TacticalCandidate", "structtess_1_1TacticalCandidate.html", null ],
    [ "tess::TacticalRequest", "structtess_1_1TacticalRequest.html", null ],
    [ "tess::TacticalScore", "structtess_1_1TacticalScore.html", null ],
    [ "tess::TickStampedEvent&lt; T &gt;", "structtess_1_1TickStampedEvent.html", null ],
    [ "tess::TileChunkDelta", "structtess_1_1TileChunkDelta.html", null ],
    [ "tess::TileDelta", "structtess_1_1TileDelta.html", null ],
    [ "tess::TileKey&lt; Shape &gt;", "structtess_1_1TileKey.html", null ],
    [ "tess::TileOccupancyIndex", "classtess_1_1TileOccupancyIndex.html", null ],
    [ "tess::TilePosition", "structtess_1_1TilePosition.html", null ],
    [ "tess::TileSpan", "structtess_1_1TileSpan.html", null ],
    [ "tess::diagnostics::TimingSnapshot", "structtess_1_1diagnostics_1_1TimingSnapshot.html", null ],
    [ "tess::TopologyBuildResult", "structtess_1_1TopologyBuildResult.html", null ],
    [ "tess::TopologyRebuildDesc", "structtess_1_1TopologyRebuildDesc.html", null ],
    [ "tess::TopologyVersion", "structtess_1_1TopologyVersion.html", null ],
    [ "tess::diagnostics::TraceBuffer", "classtess_1_1diagnostics_1_1TraceBuffer.html", null ],
    [ "tess::diagnostics::TraceCategoryStats", "structtess_1_1diagnostics_1_1TraceCategoryStats.html", null ],
    [ "tess::diagnostics::TraceRecord", "structtess_1_1diagnostics_1_1TraceRecord.html", null ],
    [ "tess::TransitionProbe&lt; Cost &gt;", "structtess_1_1TransitionProbe.html", null ],
    [ "tess::UInt128", "structtess_1_1UInt128.html", null ],
    [ "tess::movement::UnitCost", "structtess_1_1movement_1_1UnitCost.html", null ],
    [ "tess::UnitRouteCache", "classtess_1_1UnitRouteCache.html", null ],
    [ "tess::UnitRouteCacheLimits", "structtess_1_1UnitRouteCacheLimits.html", null ],
    [ "tess::UnitRouteCacheStats", "structtess_1_1UnitRouteCacheStats.html", null ],
    [ "tess::gpu::UploadDesc", "structtess_1_1gpu_1_1UploadDesc.html", null ],
    [ "tess::version", "structtess_1_1version.html", null ],
    [ "tess::diagnostics::Warning", "structtess_1_1diagnostics_1_1Warning.html", null ],
    [ "tess::gpu::WebGpuBackend", "classtess_1_1gpu_1_1WebGpuBackend.html", null ],
    [ "tess::gpu::WebGpuBackendConfig", "structtess_1_1gpu_1_1WebGpuBackendConfig.html", null ],
    [ "tess::gpu::WebGpuProductDesc", "structtess_1_1gpu_1_1WebGpuProductDesc.html", null ],
    [ "tess::WeightedPathBatchScratch", "classtess_1_1WeightedPathBatchScratch.html", null ],
    [ "tess::WeightedPathBatchStats", "structtess_1_1WeightedPathBatchStats.html", null ],
    [ "tess::WeightedPortalReplanStats", "structtess_1_1WeightedPortalReplanStats.html", null ],
    [ "tess::WeightedPortalRouteProduct", "classtess_1_1WeightedPortalRouteProduct.html", null ],
    [ "tess::WeightedPortalSegmentCache", "classtess_1_1WeightedPortalSegmentCache.html", null ],
    [ "tess::WeightedRouteProduct", "classtess_1_1WeightedRouteProduct.html", null ],
    [ "tess::detail::WorkerPoolExceptionState&lt; CaptureExceptions &gt;", null, [
      [ "tess::WorkerPoolPhaseExecutorImpl< has_exceptions >", "classtess_1_1WorkerPoolPhaseExecutorImpl.html", null ],
      [ "tess::WorkerPoolPhaseExecutorImpl< false >", "classtess_1_1WorkerPoolPhaseExecutorImpl.html", null ],
      [ "tess::WorkerPoolPhaseExecutorImpl< CaptureExceptions >", "classtess_1_1WorkerPoolPhaseExecutorImpl.html", null ]
    ] ],
    [ "tess::World&lt; Shape, Schema, Residency &gt;", "classtess_1_1World.html", null ],
    [ "tess::World&lt; Shape, Schema, AlwaysResident &gt;", "classtess_1_1World_3_01Shape_00_01Schema_00_01AlwaysResident_01_4.html", null ],
    [ "tess::World&lt; Shape, Schema, SparseResident &gt;", "classtess_1_1World_3_01Shape_00_01Schema_00_01SparseResident_01_4.html", null ],
    [ "tess::WorldArchiveInfo", "structtess_1_1WorldArchiveInfo.html", null ],
    [ "tess::WorldArchiveResult", "structtess_1_1WorldArchiveResult.html", null ],
    [ "tess::WorldArchiveSaveResult", "structtess_1_1WorldArchiveSaveResult.html", null ]
];