var searchData=
[
  ['navigationconnection_0',['NavigationConnection',['../structtess_1_1NavigationConnection.html',1,'tess']]],
  ['navigationdomain_1',['NavigationDomain',['../classtess_1_1NavigationDomain.html',1,'tess']]],
  ['navigationgoal_2',['NavigationGoal',['../structtess_1_1NavigationGoal.html',1,'tess']]],
  ['navigationgraph_3',['NavigationGraph',['../classtess_1_1NavigationGraph.html',1,'tess']]],
  ['navigationgrid_4',['NavigationGrid',['../classtess_1_1NavigationGrid.html',1,'tess']]],
  ['navigationguidance_5',['NavigationGuidance',['../structtess_1_1NavigationGuidance.html',1,'tess']]],
  ['navigationlimits_6',['NavigationLimits',['../structtess_1_1NavigationLimits.html',1,'tess']]],
  ['navigationlocaledge_7',['NavigationLocalEdge',['../structtess_1_1NavigationLocalEdge.html',1,'tess']]],
  ['navigationlocation_8',['NavigationLocation',['../structtess_1_1NavigationLocation.html',1,'tess']]],
  ['navigationpreparationdiagnostic_9',['NavigationPreparationDiagnostic',['../structtess_1_1NavigationPreparationDiagnostic.html',1,'tess']]],
  ['navigationquery_10',['NavigationQuery',['../classtess_1_1NavigationQuery.html',1,'tess::NavigationQuery'],['../classtess_1_1NavigationQuery.html#ab19c6bd7aa09e299377eff616d32345a',1,'tess::NavigationQuery::NavigationQuery(std::shared_ptr&lt; const NavigationSnapshot &gt; snapshot, NavigationLocation goal, NavigationLimits limits={})'],['../classtess_1_1NavigationQuery.html#ad41597a1cdba7cc3b84c4f10f3fa0ef4',1,'tess::NavigationQuery::NavigationQuery(std::shared_ptr&lt; const NavigationSnapshot &gt; snapshot, std::vector&lt; NavigationGoal &gt; goals, NavigationLimits limits={})']]],
  ['navigationregularedges_11',['NavigationRegularEdges',['../structtess_1_1NavigationRegularEdges.html',1,'tess']]],
  ['navigationresult_12',['NavigationResult',['../structtess_1_1NavigationResult.html',1,'tess']]],
  ['navigationsnapshot_13',['NavigationSnapshot',['../classtess_1_1NavigationSnapshot.html',1,'tess']]],
  ['navigationtransition_14',['NavigationTransition',['../structtess_1_1NavigationTransition.html',1,'tess']]],
  ['nearest_5ftarget_15',['nearest_target',['../classtess_1_1DistanceFieldProduct.html#a997d15f565eae71060a2f74af7ddeb59',1,'tess::DistanceFieldProduct::nearest_target(const World &amp;world, Coord3 start, const DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch) -&gt; NearestTargetResult'],['../classtess_1_1DistanceFieldProduct.html#a6c44cdad89d4337ef7b176b1a47af71c',1,'tess::DistanceFieldProduct::nearest_target(const World &amp;world, Coord3 start, const DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch, const Provider &amp;provider) -&gt; NearestTargetResult'],['../classtess_1_1DistanceFieldScratch.html#a997d15f565eae71060a2f74af7ddeb59',1,'tess::DistanceFieldScratch::nearest_target(const World &amp;world, Coord3 start, const DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch) -&gt; NearestTargetResult'],['../classtess_1_1DistanceFieldScratch.html#a6c44cdad89d4337ef7b176b1a47af71c',1,'tess::DistanceFieldScratch::nearest_target(const World &amp;world, Coord3 start, const DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch, const Provider &amp;provider) -&gt; NearestTargetResult']]],
  ['nearestbatchdesc_16',['NearestBatchDesc',['../structtess_1_1NearestBatchDesc.html',1,'tess']]],
  ['nearestbatchhandle_17',['NearestBatchHandle',['../structtess_1_1NearestBatchHandle.html',1,'tess']]],
  ['nearesttargetresult_18',['NearestTargetResult',['../structtess_1_1NearestTargetResult.html',1,'tess']]],
  ['nogpubackend_19',['NoGpuBackend',['../structtess_1_1gpu_1_1NoGpuBackend.html',1,'tess::gpu']]],
  ['not_20',['Not',['../structtess_1_1movement_1_1Not.html',1,'tess::movement']]],
  ['notify_5fdevice_5ferror_21',['notify_device_error',['../classtess_1_1gpu_1_1WebGpuBackend.html#a96076c8ad2831e6bf273b199757bcf10',1,'tess::gpu::WebGpuBackend']]],
  ['notify_5fdevice_5flost_22',['notify_device_lost',['../classtess_1_1gpu_1_1WebGpuBackend.html#acd47b9d02843999e4eeff9de147e3437',1,'tess::gpu::WebGpuBackend']]],
  ['notzero_23',['NotZero',['../structtess_1_1movement_1_1NotZero.html',1,'tess::movement']]],
  ['npos_5fslot_24',['npos_slot',['../classtess_1_1World_3_01Shape_00_01Schema_00_01SparseResident_01_4.html#a19fd06d9222d02acd1e49393791bb631',1,'tess::World&lt; Shape, Schema, SparseResident &gt;']]],
  ['nullwarningsink_25',['NullWarningSink',['../structtess_1_1diagnostics_1_1NullWarningSink.html',1,'tess::diagnostics']]]
];
