var searchData=
[
  ['build_5farea_5findex_0',['build_area_index',['../classtess_1_1AreaIndexScratch.html#ab697e6acff48f2cf70738d0356e44509',1,'tess::AreaIndexScratch::build_area_index()'],['../classtess_1_1AreaIndex.html#acec0afeec02725e33e19144c1c72a63b',1,'tess::AreaIndex::build_area_index()']]],
  ['build_5fdistance_5ffield_1',['build_distance_field',['../classtess_1_1DistanceFieldScratch.html#a04f6eace519daf19ff1b211e09d3a98f',1,'tess::DistanceFieldScratch']]],
  ['build_5fdistance_5ffield_5fproduct_2',['build_distance_field_product',['../classtess_1_1DistanceFieldProduct.html#acc8763fa52909ca8ca01174d20692afa',1,'tess::DistanceFieldProduct::build_distance_field_product(const World &amp;world, const GoalSet &amp;goals, DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch) -&gt; DistanceFieldResult'],['../classtess_1_1DistanceFieldProduct.html#a27b35fcaefff284c84b4b63806724167',1,'tess::DistanceFieldProduct::build_distance_field_product(const World &amp;world, const GoalSet &amp;goals, DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch, const Provider &amp;provider) -&gt; DistanceFieldResult'],['../classtess_1_1DistanceFieldScratch.html#acc8763fa52909ca8ca01174d20692afa',1,'tess::DistanceFieldScratch::build_distance_field_product(const World &amp;world, const GoalSet &amp;goals, DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch) -&gt; DistanceFieldResult'],['../classtess_1_1DistanceFieldScratch.html#a27b35fcaefff284c84b4b63806724167',1,'tess::DistanceFieldScratch::build_distance_field_product(const World &amp;world, const GoalSet &amp;goals, DistanceFieldProduct &amp;product, DistanceFieldScratch &amp;scratch, const Provider &amp;provider) -&gt; DistanceFieldResult']]],
  ['build_5flocal_5fchunk_5ftopology_3',['build_local_chunk_topology',['../classtess_1_1LocalTopologyScratch.html#a37c9ce25708606841efd81f900ac4b21',1,'tess::LocalTopologyScratch::build_local_chunk_topology()'],['../classtess_1_1LocalChunkTopology.html#aeae15e5d2bc8b16b8afbcb79402d762d',1,'tess::LocalChunkTopology::build_local_chunk_topology()']]],
  ['build_5fregion_5fgraph_4',['build_region_graph',['../classtess_1_1RegionGraphT.html#a6a5722f676e659a251ab3fda31c6c014',1,'tess::RegionGraphT']]],
  ['build_5fweighted_5fchunk_5fportal_5froute_5fproduct_5',['build_weighted_chunk_portal_route_product',['../classtess_1_1WeightedPortalRouteProduct.html#a3040e8389df656b6b9081f31ca2c3a68',1,'tess::WeightedPortalRouteProduct']]],
  ['build_5fweighted_5fchunk_5fportal_5froute_5fproduct_5fcached_6',['build_weighted_chunk_portal_route_product_cached',['../classtess_1_1WeightedPortalRouteProduct.html#a0db2de859e567fe79bc8ea64d4ccc21a',1,'tess::WeightedPortalRouteProduct']]],
  ['build_5fweighted_5fdistance_5ffield_7',['build_weighted_distance_field',['../classtess_1_1DistanceFieldScratch.html#a08ba3510db6d295a3f86fdc72ac5433d',1,'tess::DistanceFieldScratch::build_weighted_distance_field(const WorldType &amp;world, Coord3 goal, DistanceFieldScratch &amp;scratch, MissingChunkPolicy policy=MissingChunkPolicy::ReportIndeterminate) -&gt; DistanceFieldResult'],['../classtess_1_1DistanceFieldScratch.html#a9bafbe2b91c7d5261de4b3acaf606aa5',1,'tess::DistanceFieldScratch::build_weighted_distance_field(const WorldType &amp;world, Coord3 goal, DistanceFieldScratch &amp;scratch, MissingChunkPolicy policy, const Provider &amp;provider) -&gt; DistanceFieldResult']]],
  ['build_5fweighted_5fdistance_5ffield_5fin_5fbox_8',['build_weighted_distance_field_in_box',['../classtess_1_1DistanceFieldScratch.html#aafdbbfce66bb2e461af6cbb8129bc74e',1,'tess::DistanceFieldScratch::build_weighted_distance_field_in_box(const World &amp;world, Coord3 goal, Box3 domain, DistanceFieldScratch &amp;scratch, MissingChunkPolicy policy, const Provider &amp;provider) -&gt; DistanceFieldResult'],['../classtess_1_1DistanceFieldScratch.html#ac4dd57f5031c7e525612c416a745fc80',1,'tess::DistanceFieldScratch::build_weighted_distance_field_in_box(const World &amp;world, Coord3 goal, Box3 domain, DistanceFieldScratch &amp;scratch, MissingChunkPolicy policy=MissingChunkPolicy::ReportIndeterminate) -&gt; DistanceFieldResult']]],
  ['build_5fweighted_5fdistance_5ffield_5fproduct_9',['build_weighted_distance_field_product',['../classtess_1_1DistanceFieldProduct.html#a4b429f479aba8995ca172e721a1ed23a',1,'tess::DistanceFieldProduct::build_weighted_distance_field_product()'],['../classtess_1_1DistanceFieldScratch.html#a4b429f479aba8995ca172e721a1ed23a',1,'tess::DistanceFieldScratch::build_weighted_distance_field_product()']]],
  ['build_5fweighted_5fportal_5froute_5fproduct_10',['build_weighted_portal_route_product',['../classtess_1_1WeightedPortalRouteProduct.html#a0cf7ab372be054546a581adfbd2430f0',1,'tess::WeightedPortalRouteProduct::build_weighted_portal_route_product(const World &amp;world, PathRequest request, std::span&lt; const Coord3 &gt; waypoints, PathScratch &amp;scratch, WeightedPortalRouteProduct &amp;product) -&gt; PathResult'],['../classtess_1_1WeightedPortalRouteProduct.html#ab1ca122c087b7b78b7f27812051668a9',1,'tess::WeightedPortalRouteProduct::build_weighted_portal_route_product(const World &amp;world, PathRequest request, std::span&lt; const Coord3 &gt; waypoints, PathScratch &amp;scratch, WeightedPortalSegmentCache &amp;cache, WeightedPortalRouteProduct &amp;product) -&gt; PathResult']]],
  ['build_5fweighted_5froute_5fproduct_11',['build_weighted_route_product',['../classtess_1_1WeightedRouteProduct.html#aff8069d8c0c7f1a46426c9df74fc8486',1,'tess::WeightedRouteProduct']]]
];
