var createTessWebGpu=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var Module=moduleArg;var l="",m;try{l=(new URL(".",_scriptName)).href}catch{}m=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var t=console.error.bind(console),v=!1,w;function x(){if(!y?.buffer?.resizable){var a=z.buffer;y=new Int8Array(a);new Int16Array(a);A=new Uint8Array(a);new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);new Float32Array(a);D=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}}
function aa(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),ba.push(...a));for(a=ba;a.length>0;)a.shift()(Module)}function ca(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),da.push(...a));for(a=da;a.length>0;)a.shift()(Module)}function E(a){Module.onAbort?.(a);a=`Aborted(${a})`;t(a);v=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ea;
async function fa(a){try{var b=await m(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}async function ha(a,b){try{var c=await fa(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),E(d)}}
async function ia(a){var b=ea;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return ha(b,a)}class ja{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var B,y,D,C,A,da=[],ba=[],F=!0;class ka{constructor(a){this.M=a-24}init(a,b){C[this.M+16>>2]=0;C[this.M+4>>2]=a;C[this.M+8>>2]=b}}
var la=0,I=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}var e=b+1;b=G(e);c=b;d=A;if(e>0){e=c+e-1;for(var g=0;g<a.length;++g){var k=a.codePointAt(g);if(k<=127){if(c>=e)break;d[c++]=k}else if(k<=2047){if(c+1>=e)break;d[c++]=192|k>>6;d[c++]=128|k&63}else if(k<=65535){if(c+2>=e)break;d[c++]=224|k>>12;d[c++]=128|k>>6&63;d[c++]=128|k&63}else{if(c+3>=e)break;d[c++]=240|k>>18;d[c++]=128|k>>12&63;d[c++]=128|k>>6&63;d[c++]=128|k&63;g++}}d[c]=
0}return b},ma=globalThis.TextDecoder&&new TextDecoder,J=(a=0,b)=>{var c=A;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(d-a>16&&c.buffer&&ma)return ma.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var g=c[a++]&63;if((e&224)==192)b+=String.fromCharCode((e&31)<<6|g);else{var k=c[a++]&63;e=(e&240)==224?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|c[a++]&63;e<65536?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},K=a=>
C[a>>2]+B[a+4>>2]*4294967296,L=[],na=(a,b)=>{L[a>>>0]=b},M=[],N=a=>{if(a)return L[a>>>0]},oa=(a,b)=>{for(a=C[a>>2];a;a=C[a>>2])b[B[a+4>>2]](a)},pa=a=>{var b=C[a>>2];return b?J(b,C[a+4>>2]):""},O=a=>{var b=C[a>>2];a=C[a+4>>2];if(b)return b?J(b,a):"";if(a===0)return""},qa=[,"compatibility","core"],ra={1:"core-features-and-limits",2:"depth-clip-control",3:"depth32float-stencil8",4:"texture-compression-bc",5:"texture-compression-bc-sliced-3d",6:"texture-compression-etc2",7:"texture-compression-astc",
8:"texture-compression-astc-sliced-3d",9:"timestamp-query",10:"indirect-first-instance",11:"shader-f16",12:"rg11b10ufloat-renderable",13:"bgra8unorm-storage",14:"float32-filterable",15:"float32-blendable",16:"clip-distances",17:"dual-source-blending",18:"subgroups",19:"texture-formats-tier1",20:"texture-formats-tier2",21:"primitive-index",22:"texture-component-swizzle",327692:"chromium-experimental-unorm16-texture-formats",327729:"chromium-experimental-multi-draw-indirect"},sa=[,"low-power","high-performance"],
ta={undefined:1,unknown:1,destroyed:2},P=a=>{if(!(a instanceof ja||a=="unwind"))throw a;},ua=a=>{w=a;F||(Module.onExit?.(a),v=!0);throw new ja(a);},Q=a=>{if(!v)try{a()}catch(b){P(b)}finally{if(!F)try{w=a=w,ua(a)}catch(b){P(b)}}},R=a=>a<-9007199254740992||a>9007199254740992?NaN:Number(a),va=(a,b,c,d)=>{var e={string:n=>{var h=0;n!==null&&n!==void 0&&n!==0&&(h=I(n));return h},array:n=>{var h=G(n.length);y.set(n,h);return h}};a=Module["_"+a];var g=[],k=0;if(d)for(var f=0;f<d.length;f++){var p=e[c[f]];
p?(k===0&&(k=S()),g[f]=p(d[f])):g[f]=d[f]}c=a(...g);return c=function(n){k!==0&&T(k);return b==="string"?n?J(n):"":b==="boolean"?!!n:n}(c)};Module.noExitRuntime&&(F=Module.noExitRuntime);Module.printErr&&(t=Module.printErr);var U=Module.preInit;if(U)for(typeof U=="function"&&(Module.preInit=U=[U]);U.length>0;)U.shift()();Module.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>g==="number"||g==="boolean");return b!=="string"&&e&&!d?Module["_"+a]:(...g)=>va(a,b,c,g)};
var wa,xa,ya,za,Aa,Ba,Ca,V,W,X,Y,Da,Ea,Fa,T,G,S,z,Ha={d:(a,b,c)=>{(new ka(a)).init(b,c);la++;E()},k:()=>E(""),j:a=>{var b=A.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-z.buffer.byteLength+65535)/65536|0;try{z.grow(d);x();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},o:function(a,b,c,d,e,g){b=R(b);c=R(c);a=N(a);var k={};if(g){var f=C[g+12>>2];if(f){var p=C[g+16>>
2];k.requiredFeatures=Array.from(C.subarray(p>>2,p+f*4>>2),h=>ra[h])}if(f=C[g+20>>2]){p=C[f>>2];var n={};function h(u,r,H,Ga=!1){r=C[r+H>>2];r==4294967295||Ga&&r==0||(n[u]=r)}function q(u,r,H){r+=H;H=C[r+4>>2];if(C[r>>2]!=4294967295||H!=4294967295)n[u]=K(r)}h("maxTextureDimension1D",f,4);h("maxTextureDimension2D",f,8);h("maxTextureDimension3D",f,12);h("maxTextureArrayLayers",f,16);h("maxBindGroups",f,20);h("maxBindGroupsPlusVertexBuffers",f,24);h("maxBindingsPerBindGroup",f,28);h("maxDynamicUniformBuffersPerPipelineLayout",
f,32);h("maxDynamicStorageBuffersPerPipelineLayout",f,36);h("maxSampledTexturesPerShaderStage",f,40);h("maxSamplersPerShaderStage",f,44);h("maxStorageBuffersPerShaderStage",f,48);h("maxStorageTexturesPerShaderStage",f,52);h("maxUniformBuffersPerShaderStage",f,56);h("minUniformBufferOffsetAlignment",f,80);h("minStorageBufferOffsetAlignment",f,84);q("maxUniformBufferBindingSize",f,64);q("maxStorageBufferBindingSize",f,72);h("maxVertexBuffers",f,88);q("maxBufferSize",f,96);h("maxVertexAttributes",f,
104);h("maxVertexBufferArrayStride",f,108);h("maxInterStageShaderVariables",f,112);h("maxColorAttachments",f,116);h("maxColorAttachmentBytesPerSample",f,120);h("maxComputeWorkgroupStorageSize",f,124);h("maxComputeInvocationsPerWorkgroup",f,128);h("maxComputeWorkgroupSizeX",f,132);h("maxComputeWorkgroupSizeY",f,136);h("maxComputeWorkgroupSizeZ",f,140);h("maxComputeWorkgroupsPerDimension",f,144);h("maxImmediateSize",f,148,!0);p!==0&&"maxStorageBuffersInVertexStage"in GPUSupportedLimits.prototype&&(h("maxStorageBuffersInVertexStage",
p,8),h("maxStorageTexturesInVertexStage",p,12),h("maxStorageBuffersInFragmentStage",p,16),h("maxStorageTexturesInFragmentStage",p,20));k.requiredLimits=n}if(f=C[g+24>>2])f={label:O(f+4)},k.defaultQueue=f;k.label=O(g+4)}a.requestDevice(k).then(h=>{Q(()=>{L[e>>>0]=h.queue;L[d>>>0]=h;h.lost.then(q=>{Q(()=>{h.onuncapturederror=()=>{};var u=S(),r=I(q.message);V(c,ta[q.reason],r);T(u)})});h.onuncapturederror=q=>{var u=5;q.error instanceof GPUValidationError?u=2:q.error instanceof GPUOutOfMemoryError?u=
3:q.error instanceof GPUInternalError&&(u=4);var r=S();q=I(q.error.message);Da(d,u,q);T(r)};Y(b,1,d,0)})},h=>{Q(()=>{var q=S(),u=I(h.message);Y(b,3,d,u);c&&V(c,4,u);T(q)})})},t:(a,b,c)=>{var d=N(a);c==-1&&(c=void 0);try{var e=d.getMappedRange(b,c)}catch(k){return 0}var g=Fa(16,e.byteLength);A.set(new Uint8Array(e),g);M[a].push(()=>Ea(g));return g},s:function(a,b,c,d,e){b=R(b);c=R(c);var g=N(a);M[a]=[];e==-1&&(e=void 0);g.mapAsync(c,d,e).then(()=>{Q(()=>{W(b,1,0)})},k=>{Q(()=>{S();var f=I(k.message);
W(b,k.name==="AbortError"?4:k.name==="OperationError"?3:0,f);delete M[a]})})},r:a=>{var b=N(a),c=M[a];if(c){for(var d=0;d<c.length;++d)c[d]();delete M[a];b.unmap()}},a:a=>{delete L[a]},n:(a,b,c)=>{var d=!!C[b+32>>2];b={label:O(b+4),usage:C[b+16>>2],size:K(b+24),mappedAtCreation:d};a=N(a);try{var e=a.createBuffer(b)}catch(g){return!1}L[c>>>0]=e;d&&(M[c]=[]);return!0},m:(a,b,c)=>{var d=C[b>>2],e=B[d+4>>2];b={label:O(b+4),code:""};switch(e){case 2:b.code=pa(d+8)}a=N(a).createShaderModule(b);L[c>>>0]=
a},p:a=>{a=N(a);a.onuncapturederror=null;a.destroy()},l:function(a,b,c,d){b=R(b);if(c){var e={featureLevel:qa[B[c+4>>2]],powerPreference:sa[B[c+8>>2]],forceFallbackAdapter:!!C[c+12>>2]};a=C[c>>2];a!==0&&(e.N=!!C[a+8>>2])}"gpu"in navigator?navigator.gpu.requestAdapter(e).then(g=>{Q(()=>{if(g)L[d>>>0]=g,X(b,1,d,0);else{var k=S(),f=I("WebGPU not available on this browser (requestAdapter returned null)");X(b,3,d,f);T(k)}})},g=>{Q(()=>{var k=S(),f=I(g.message);X(b,4,d,f);T(k)})}):(e=S(),a=I("WebGPU not available on this browser (navigator.gpu is not available)"),
X(b,3,d,a),T(e))},c:function(a){return BigInt(N(a).size)},i:function(a){return BigInt(N(a).usage)},g:(a,b)=>{if(b){var c=O(b+4);b=C[b+12>>2];b=b!==0?{querySet:N(C[b+4>>2]),beginningOfPassWriteIndex:C[b+8>>2],endOfPassWriteIndex:C[b+12>>2]}:void 0;c={label:c,timestampWrites:b}}b=N(a);a=Ba(0);c=b.beginComputePass(c);L[a>>>0]=c;return a},w:function(a,b,c,d,e,g){c=R(c);e=R(e);g=R(g);N(a).copyBufferToBuffer(N(b),c,N(d),e,g)},v:a=>{var b=N(a);a=za(0);b=b.finish();L[a>>>0]=b;return a},y:(a,b,c,d)=>{N(a).dispatchWorkgroups(b,
c,d)},x:a=>{N(a).end()},e:(a,b,c,d,e)=>{a=N(a);c=N(c);d==0?a.setBindGroup(b,c):a.setBindGroup(b,c,C,e>>2,d)},f:(a,b)=>{N(a).setPipeline(N(b))},z:(a,b)=>{var c=N(a);a=ya(0);b=c.getBindGroupLayout(b);L[a>>>0]=b;return a},q:(a,b)=>{function c(e){var g=C[e+8>>2],k=C[e+32>>2],f=C[e+36>>2],p=0;oa(e,{14:n=>{p=C[n+8>>2]}});g?(k=K(e+24),k==-1&&(k=void 0),g={buffer:N(g),offset:K(e+16),size:k}):g=N(k||f||p);return{binding:C[e+4>>2],resource:g}}b={label:O(b+4),layout:N(C[b+12>>2]),entries:function(e,g){for(var k=
[],f=0;f<e;++f)k.push(c(g+40*f));return k}(C[b+16>>2],C[b+20>>2])};a=N(a);var d=xa(0);na(d,a.createBindGroup(b));return d},b:(a,b)=>{var c;b&&(c={label:O(b+4)});b=N(a);a=Aa(0);c=b.createCommandEncoder(c);L[a>>>0]=c;return a},A:(a,b)=>{var c=O(b+4);var d=(d=C[b+12>>2])?N(d):"auto";if(b+=16){var e=N(C[b+4>>2]);var g=C[b+16>>2];var k=C[b+20>>2];if(g){for(var f={},p=0;p<g;++p){var n=k+24*p,h=pa(n+4);f[h]=D[n+16>>3]}g=f}else g=void 0;b={module:e,constants:g,entryPoint:O(b+8)}}else b=void 0;c={label:c,
layout:d,compute:b};d=N(a);a=Ca(0);c=d.createComputePipeline(c);L[a>>>0]=c;return a},u:(a,b,c)=>{a=N(a);b=Array.from(B.subarray(c>>2,c+b*4>>2),d=>N(d));a.submit(b)},h:function(a,b,c,d,e){c=R(c);N(a).writeBuffer(N(b),c,A.subarray(d,d+e),0,e)}};function Ia(){var a=wa;try{var b=a(0,0);w=b;ua(b)}catch(c){P(c)}}var Z;
Z=await (async function(){function a(d){d=Z=d.exports;Module._tess_webgpu_status=d.D;wa=Module._main=d.F;xa=d.G;ya=d.H;za=d.I;Aa=d.J;Ba=d.K;Ca=d.L;V=d.aa;W=d.ba;X=d.ca;Y=d.da;Da=d.ea;Ea=d.fa;Fa=d.ha;T=d.ia;G=d.ja;S=d.ka;z=d.B;x();return Z}var b={a:Ha},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ea??=Module.locateFile?Module.locateFile("tess-webgpu.wasm",l):l+"tess-webgpu.wasm";return function(d){return a(d.instance)}(await ia(b))}());
await (async function(){aa();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));v||(Z.C(),Module.onRuntimeInitialized?.(),Module.noInitialRun||Ia(),ca())}());
;return Module}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createTessWebGpu;module.exports.default=createTessWebGpu}else if(typeof define==="function"&&define["amd"])define([],()=>createTessWebGpu);
