var searchData=
[
  ['pathview_0',['PathView',['../classtess_1_1PathView.html#a609ac007f0a5d9611696fa41d4d1facd',1,'tess::PathView::PathView() noexcept=default'],['../classtess_1_1PathView.html#ae728e1e7d9af7c3736e92e7cf0768bc9',1,'tess::PathView::PathView(std::span&lt; const Coord3 &gt; nodes) noexcept'],['../classtess_1_1PathView.html#ab5bf5d70b83e0c69f6520ff102aa672d',1,'tess::PathView::PathView(const std::vector&lt; Coord3 &gt; &amp;nodes) noexcept'],['../classtess_1_1PathView.html#aef96744a5704c4f039a834ab5abfdce7',1,'tess::PathView::PathView(std::vector&lt; Coord3 &gt; &amp;&amp;)=delete'],['../classtess_1_1PathView.html#a38a4ec534b5a9b461ffdada501ae34bf',1,'tess::PathView::PathView(const std::vector&lt; Coord3 &gt; &amp;&amp;)=delete']]],
  ['policy_5fmatches_1',['policy_matches',['../classtess_1_1ExecutionPhase.html#a2b87b4d9efea32fcd1ffd8cd39bdbea2',1,'tess::ExecutionPhase']]],
  ['portal_5fsegment_5fcache_2',['portal_segment_cache',['../classtess_1_1PathRequestRuntime.html#a663344b7159d1859b7dde7ddfd48030d',1,'tess::PathRequestRuntime::portal_segment_cache() noexcept -&gt; WeightedPortalSegmentCache &amp;'],['../classtess_1_1PathRequestRuntime.html#a435417c387066207f96bbe1d17adaaf6',1,'tess::PathRequestRuntime::portal_segment_cache() const noexcept -&gt; const WeightedPortalSegmentCache &amp;']]],
  ['process_5funit_5fcached_3',['process_unit_cached',['../classtess_1_1PathRequestRuntime.html#aa34d9e94df468febd48a166b68bbc935',1,'tess::PathRequestRuntime::process_unit_cached(const World &amp;world, PathRuntimeCachePolicy policy={}, const RegionGraphT&lt; typename World::residency_type &gt; *graph=nullptr) -&gt; std::span&lt; const PathResult &gt;'],['../classtess_1_1PathRequestRuntime.html#a5e8ca2d0de7e60a8017b972fec49a7f3',1,'tess::PathRequestRuntime::process_unit_cached(const World &amp;world, PathRuntimeCachePolicy policy, const RegionGraphT&lt; typename World::residency_type &gt; *graph, const Provider &amp;provider) -&gt; std::span&lt; const PathResult &gt;']]],
  ['process_5fweighted_5fbatch_4',['process_weighted_batch',['../classtess_1_1PathRequestRuntime.html#af4eee57c3152b6f4cb2b4d74b29ae9c7',1,'tess::PathRequestRuntime::process_weighted_batch(const World &amp;world, PathRuntimeCachePolicy policy={}, const RegionGraphT&lt; typename World::residency_type &gt; *graph=nullptr) -&gt; std::span&lt; const PathResult &gt;'],['../classtess_1_1PathRequestRuntime.html#aa79f41a7cd327b1e3310a44d70fa87f6',1,'tess::PathRequestRuntime::process_weighted_batch(const World &amp;world, PathRuntimeCachePolicy policy, const RegionGraphT&lt; typename World::residency_type &gt; *graph, const Provider &amp;provider) -&gt; std::span&lt; const PathResult &gt;']]],
  ['product_5',['product',['../classtess_1_1experimental_1_1maintenance_1_1ChunkMaintenanceAdapter.html#a3eaeac9ffa280a24cdb9fca488a5bba6',1,'tess::experimental::maintenance::ChunkMaintenanceAdapter']]]
];
