include_guard(GLOBAL)

set(TESS_CMAKE_HAS_MODULE_SCAN OFF)
set(TESS_FETCHCONTENT_EXCLUDE_FROM_ALL)

if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.28)
  set(TESS_CMAKE_HAS_MODULE_SCAN ON)
  set(TESS_FETCHCONTENT_EXCLUDE_FROM_ALL EXCLUDE_FROM_ALL)
endif()
