set(TESS_VERSION 1.0.0)
set(TESS_VERSION_PRERELEASE "rc.1")

set(TESS_VERSION_STRING "${TESS_VERSION}")
if(NOT TESS_VERSION_PRERELEASE STREQUAL "")
  string(APPEND TESS_VERSION_STRING "-${TESS_VERSION_PRERELEASE}")
endif()
