set(TESS_VERSION 0.12.0)
set(TESS_VERSION_PRERELEASE "")

set(TESS_VERSION_STRING "${TESS_VERSION}")
if(NOT TESS_VERSION_PRERELEASE STREQUAL "")
  string(APPEND TESS_VERSION_STRING "-${TESS_VERSION_PRERELEASE}")
endif()
